nodeLinker: node-modules
enableGlobalCache: true
cacheFolder: "D:/dev/nvm/yarn4_cache"
globalFolder: "D:/dev/nvm/yarn4_global"
npmRegistryServer: "https://registry.npmmirror.com/"
enableStrictSsl: false
